--[[-- INFO -------------------------------------------------------------------
	File				: avo_controller
	Description	: Mod orchestration script
	Credits			: aVo, Alundaio
	Revision		: 2.0
	Change Date	: 07.30.2013 complete redesign
--]] --------------------------------------------------------------------------
--/----------------------------------------------------------------------------
--/ Variables
--/----------------------------------------------------------------------------
local sname = script_name() --/ script name

--/----------------------------------------------------------------------------
--/ Initialization
--/----------------------------------------------------------------------------
function _init()
	avo_global._init() --/ initialize global functions
	-- avo_lua_utils._init()
	-- avo_log._init()
end
