--[[-- INFO -------------------------------------------------------------------
	File				: avo_log
	Description	: Logging functions
	Credits			: aVo
	Revision		: 0.2
	Change Date	: 07.26.2013 (-init)
--]] --------------------------------------------------------------------------

--/----------------------------------------------------------------------------
--/ xray extensions replacement for non-functional log
--/----------------------------------------------------------------------------
function log(msg, ...)
  if log1 then 
		log1(msg)
	else
		get_console():execute("load ~:"..msg)
	end
end
--/----------------------------------------------------------------------------
--/ xray extensions replacement for non-functional flush
--/----------------------------------------------------------------------------
function flush()
  if flush1 then 
		flush1()
	else
		get_console():execute('flush')
	end
end
--/----------------------------------------------------------------------------
--/ Add debug information (script name, current line) if available
--/----------------------------------------------------------------------------
function dbg_format(...)
	local arg = {...}
	if #arg == 0 then return '<<zero string>>' end
	local stack_depth = 3 -- default stack depth
	if type(arg[1]) == 'number' and #arg > 1 then -- stack depth override
		stack_depth = table.remove(arg, 1) -- shift first value
	end
	if debug == nil then return avo_lua.format_ext(unpack(arg)) end -- debug not available
	if type(arg[1]) == 'string' then
		local fn_name = string.match(arg[1], '^%(.-:(.*)%)') or '' -- save function name
		arg[1] = string.gsub(arg[1],'^%(.*%)', fn_name) -- remove script name when debug is on (already part of trace info_table)
	-- else
		-- return 'dbg_format: cannot format passed expression'
	end
	local info_table = debug.getinfo(stack_depth)
	if not info_table then return avo_lua.format_ext(unpack(arg)) end
	local script = string.get_filename(info_table.short_src)
	return string.format("(%s:%d) %s", script, info_table.currentline, avo_lua.format_ext(unpack(arg))) -- dependent on avo_lua
end
--/----------------------------------------------------------------------------
--/ Error log
--/----------------------------------------------------------------------------
function elog(...)
  log(avo_lua.format_ext("[ERROR] %s", dbg_format(...))) 
end
--/----------------------------------------------------------------------------
--/ Debug (info) log
--/----------------------------------------------------------------------------
function dlog(...)
	log(avo_lua.format_ext("[DEBUG] %s", dbg_format(...)))
end
--/----------------------------------------------------------------------------
--/ Warning log
--/----------------------------------------------------------------------------
function wlog(...)
	log(avo_lua.format_ext("[WARN] %s", dbg_format(...)))
end
--/----------------------------------------------------------------------------
--/ printf (XRay) log
--/----------------------------------------------------------------------------
function printf(...)
	log(avo_lua.format_ext("[XRAY] %s", dbg_format(...)))
end
--/----------------------------------------------------------------------------
--/ Visual log (show in-game message)
--/----------------------------------------------------------------------------
local bufferedmessages = {}
function vlog(...)
	local msg = dbg_format(...)
	log(avo_lua.format_ext("[VLOG] %s", msg)) --/ save to log as well
	if msg then
		table.insert(bufferedmessages, msg)
	end
	if db and db.actor and #bufferedmessages > 0 then
		for _, msg in ipairs(bufferedmessages) do
			db.actor:give_game_news("VLOG", msg, "ui_inGame2_PD_Lider", 0, 15000)
		end
		bufferedmessages={}
	end
end