--[[-- INFO -------------------------------------------------------------------
	File				: avo_string.script
	Description	: String functions
	Credits			: aVo
	Revision		: 0.1
	Change Date	: Wed 12/05/2012
--]] --------------------------------------------------------------------------
--/----------------------------------------------------------------------------
--/ Split string by delimiter
--/ do_trim - trim whitespace? default is false
--/----------------------------------------------------------------------------
function split(str, delim, do_trim)
	local t = {}
	if type(str) ~= 'string' then
		return t
	end
	local cpt = string.find(str, delim, 1, true)
	if cpt then
		repeat
			if do_trim then
				table.insert(t, trim(string.sub(str, 1, cpt-1)))
			else
				table.insert(t, string.sub(str, 1, cpt-1))
			end
			str = string.sub(str, cpt + string.len(delim))
			cpt = string.find(str, delim, 1, true)
		until cpt == nil
	end
	if do_trim then
		table.insert(t, trim(str))
	else
		table.insert(t, str)
	end
	return t
end
--/----------------------------------------------------------------------------
--/ Trim whitespace from both sides of the string
--/----------------------------------------------------------------------------
function trim(str)
	return (string.gsub(str, "^%s*(.-)%s*$", "%1"))
end
--/----------------------------------------------------------------------------
--/ Get filename (without extension) from path
--/----------------------------------------------------------------------------
function get_filename(path)
	return tostring(string.match(trim(path), "^.*\\(.-)%.%a-$"))
end