--[[-- INFO -------------------------------------------------------------------
	File				: avo_table
	Description	: Table functions
	Credits			: aVo, xStream, Artos
	Revision		: 0.2
	Change Date	: 07.26.2013
--]] --------------------------------------------------------------------------
--/----------------------------------------------------------------------------
--/ Check if value esists in the table
--/----------------------------------------------------------------------------
function exists(val, tbl)
  for _, v in ipairs(tbl) do
    if v == val then
      return true
    end
  end
  return false
end

--/----------------------------------------------------------------------------
--/ Clone table. Usedata is not cloned
--/ with_meta - clone metatables? Default is false
--/----------------------------------------------------------------------------
function clone(object, with_meta)
  local lookup_table = {}
  local function _copy(object)
    if type(object) ~= "table" then
      return object
    elseif lookup_table[object] then
      return lookup_table[object]
    end
    local new_table = {}
    lookup_table[object] = new_table
    for index, value in pairs(object) do
      new_table[_copy(index)] = _copy(value)
    end
		if with_meta then
			return setmetatable(new_table, _copy(getmetatable(object)))
		else
			return new_table
		end
  end
  return _copy(object)
end

--/----------------------------------------------------------------------------
--/ Get number of elements in hash
--/----------------------------------------------------------------------------
function hash_size(tbl)
	num = 0
	for k,v in pairs(tbl) do
    num = num + 1
	end
	return num
end