--[[-- INFO -------------------------------------------------------------------
	File				: avo_controller
	Description	: Mod orchestration script
	Credits			: aVo, Alundaio
	Revision		: 2.0
	Change Date	: 07.30.2013 complete redesign
--]] --------------------------------------------------------------------------
--/----------------------------------------------------------------------------
--/ Variables
--/----------------------------------------------------------------------------
local self_name = script_name() --/ script name
local debug_on = false --/ enable-disable in config not here
--/----------------------------------------------------------------------------
--/ Initialization
--/----------------------------------------------------------------------------
function _init()
	dlog("in %s", self_name)
end
