--[[-- INFO -------------------------------------------------------------------
	File				: avo_math.script
	Description	: Math functions
	Credits			: aVo
	Revision		: 0.1
	Change Date	: Wed 12/05/2012
--]] --------------------------------------------------------------------------
--/----------------------------------------------------------------------------
--/ Check if the number value is a NaN (not a number). For more information on NaNs, see the IEEE 754 standards.
--/----------------------------------------------------------------------------
nan = -(0/0) --/ not a number
function isnan(value)
	return value ~= value
end
--/----------------------------------------------------------------------------
--/ Check if the number value is positive or negative infinity
--/----------------------------------------------------------------------------
inf = 1/0
function isinf(value)
	if value == -inf then
		return -1
	elseif value == inf then
		return 1
	else
		return 0
	end
end
--/----------------------------------------------------------------------------
--/ Determines if the given number value has finite value i.e. it is not infinite or NAN.
--/----------------------------------------------------------------------------
function isfinite(value)
	return value > -inf and value < inf
end
--/----------------------------------------------------------------------------
--/ Rounds a value to the nearest integer or specified number of decimal places
--/----------------------------------------------------------------------------
function round(value, decimals)
	local mul = math.pow(10,decimals) --/ 10^count
	return math.floor(value*mul +0.5)/mul
end
--/----------------------------------------------------------------------------
--/ Generates random number. If no arguments given will generate between zero and one
--/----------------------------------------------------------------------------
function rand(min_value, max_value)
	math.randomseed(device():time_global())
	if not min_value == nil and max_value == nil then
		return math.random()
	else
		return math.random(min_value, max_value)
	end
end